### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by FenrisWolffe** [SuperGouge/HearthheadCollectionManager#2]
This still does not explain how to export/import.

I realize I must be the only person who doesn't get it.. I SEE the buttons on hearthhead, but nothing in the collection tracker.

**Comment by SuperGouge** [comment]
I explained in ko-vasilev/Hearthstone-Collection-Tracker#3 that since the author doesn't have the time to accept my changes for now, you have to download my version [here](https://github.com/SuperGouge/Hearthstone-Collection-Tracker/releases/tag/0.2) until the next update of his plugin.

**Comment by FenrisWolffe** [comment]
@SuperGouge Yes, and I have done so, but it still does not seem to be working. Maybe I’m just totally missing things.

**Comment by SuperGouge** [comment]
If you deleted the original plugin and installed my version following the guide on [how to install plugins](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins) I'm afraid I can't help you more.
Here is an image of what you should see when going to `PLUGINS > Collection Tracker`:
![hearthstonecollectiontracker](https://cloud.githubusercontent.com/assets/3006175/8146557/d58fa714-1240-11e5-9849-57a3dcf7d35a.png)
